version: "3"
services:
  iRango:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: tiagorosadacosta/irango
    environment:
      NODE_ENV: prd
    command: node_modules/.bin/nodemon --exec npm start
    volumes:
      - .:/home/app/iRango
      - /home/app/iRango/node_modules
    ports:
      - 8080:80
    container_name: irango_prd
    networks:
      - prd
networks:
  prd:
    driver: bridge  